RESTCLIENTCPP_VERSION = 0.5.0.1 
RESTCLIENTCPP_SITE = $(call github,stretchdude,restclient-cpp,$(RESTCLIENTCPP_VERSION))
RESTCLIENTCPP_LICENSE =  GPL
RESTCLIENTCPP_LICENSE_FILES = LICENSE
RESTCLIENTCPP_INSTALL_STAGING = YES
RESTCLIENTCPP_INSTALL_TARGET = YES
RESTCLIENTCPP_CONF_OPTS = 

define RESTCLIENTCPP_RUN_AUTOGEN
       cd $(@D) &&  ./autogen.sh
endef

RESTCLIENTCPP_PRE_CONFIGURE_HOOKS += RESTCLIENTCPP_RUN_AUTOGEN 

$(eval $(autotools-package))


